<?php
/**
 * Generates VCL snippet for injecting the Speculation-Rules header
 * from the edge (Varnish) instead of the origin.
 *
 * Follows the same pattern as TE_I3 VCL generation.
 *
 * @package flavor_edge_cache
 */

namespace flavor_edge;

defined( 'ABSPATH' ) || exit;

class TE_VCL_Snippet {

	/**
	 * Generate the VCL snippet for Speculation Rules header injection.
	 *
	 * @param string $domain Optional domain override.
	 * @return string VCL code.
	 */
	public static function generate( $domain = '' ) {
		if ( ! $domain ) {
			$domain = wp_parse_url( home_url(), PHP_URL_HOST );
		}

		$rest_path = '/wp-json/te-cache/v1/speculation-rules';

		$vcl = <<<VCL
# ── Speculation Rules header injection ──────────────────────────
# Generated by Transparent Edge Cache plugin.
# Injects the Speculation-Rules header on HTML responses,
# pointing to the JSON endpoint served by the plugin.
#
# Deploy this in: Configuration → VCL → vcl_deliver
# ────────────────────────────────────────────────────────────────

sub vcl_deliver {
    if (resp.http.Content-Type ~ "text/html"
        && req.url !~ "^/wp-admin"
        && req.url !~ "^/wp-login"
        && req.url !~ "^/wp-json"
        && req.url !~ "^/wp-cron"
        && req.url !~ "\\.(?:css|js|png|jpg|jpeg|gif|svg|webp|woff2?|ico)(?:\\?|$)") {
        set resp.http.Speculation-Rules = {""{$rest_path}""};
    }
}

# ── Cache the Speculation Rules JSON with its own tag ───────────
# Deploy this in: Configuration → VCL → vcl_backend_response

sub vcl_backend_response {
    if (bereq.url ~ "^/wp-json/te-cache/v1/speculation-rules") {
        set beresp.http.Surrogate-Keys = beresp.http.Surrogate-Keys + " speculation-rules";
        set beresp.ttl = 3600s;
        set beresp.grace = 86400s;
    }
}
VCL;

		return $vcl;
	}
}
