<?php
/**
 * Security Headers module.
 *
 * Generates a recommended VCL snippet (for the vcl_deliver block) that the
 * client applies from their Transparent Edge panel. Never auto-deploys.
 *
 * Can also emit headers directly from WordPress as a fallback for clients
 * who cannot apply VCL (see TE_Hardening for the PHP-side emission).
 *
 * @package flavor_edge_cache
 */

namespace flavor_edge;

defined( 'ABSPATH' ) || exit;

class TE_Security_Headers {

	/**
	 * Build the recommended VCL snippet based on selected headers.
	 *
	 * @return string VCL code for the vcl_deliver block.
	 */
	public static function generate_vcl() {
		$s        = TE_Settings::get_all();
		$headers  = array();

		if ( ! empty( $s['sec_header_hsts'] ) ) {
			$max_age = (int) ( $s['sec_header_hsts_maxage'] ?? 31536000 );
			$value   = 'max-age=' . $max_age;
			if ( ! empty( $s['sec_header_hsts_subdomains'] ) ) {
				$value .= '; includeSubDomains';
			}
			if ( ! empty( $s['sec_header_hsts_preload'] ) ) {
				$value .= '; preload';
			}
			$headers['Strict-Transport-Security'] = $value;
		}

		if ( ! empty( $s['sec_header_nosniff'] ) ) {
			$headers['X-Content-Type-Options'] = 'nosniff';
		}

		if ( ! empty( $s['sec_header_referrer'] ) ) {
			$headers['Referrer-Policy'] = $s['sec_header_referrer_value'] ?? 'strict-origin-when-cross-origin';
		}

		if ( ! empty( $s['sec_header_permissions'] ) ) {
			$headers['Permissions-Policy'] = $s['sec_header_permissions_value'] ?? 'geolocation=(), microphone=(), camera=()';
		}

		if ( ! empty( $s['sec_header_frame'] ) ) {
			$headers['X-Frame-Options'] = $s['sec_header_frame_value'] ?? 'SAMEORIGIN';
		}

		if ( ! empty( $s['sec_header_csp'] ) && ! empty( $s['sec_header_csp_value'] ) ) {
			// CSP in Report-Only mode by default for safe rollout.
			$csp_header = ! empty( $s['sec_header_csp_enforce'] )
				? 'Content-Security-Policy'
				: 'Content-Security-Policy-Report-Only';
			$headers[ $csp_header ] = $s['sec_header_csp_value'];
		}

		if ( empty( $headers ) ) {
			return '';
		}

		$lines   = array();
		$lines[] = '# ── Security headers ────────────────────────────────────────';
		$lines[] = '# Generated by Transparent Edge Cache. Deploy from your panel:';
		$lines[] = '# Configuration → VCL → add to your vcl_deliver block.';
		$lines[] = '# ────────────────────────────────────────────────────────────';
		$lines[] = 'sub vcl_deliver {';
		foreach ( $headers as $name => $value ) {
			// Escape double quotes in the value for VCL string safety.
			$safe_value = str_replace( '"', '\\"', $value );
			$lines[]    = sprintf( '    set resp.http.%s = "%s";', $name, $safe_value );
		}
		$lines[] = '}';

		return implode( "\n", $lines );
	}

	/**
	 * Get the list of enabled headers for display/PHP fallback.
	 *
	 * @return array name => value
	 */
	public static function get_enabled_headers() {
		$s       = TE_Settings::get_all();
		$headers = array();

		if ( ! empty( $s['sec_header_hsts'] ) ) {
			$max_age = (int) ( $s['sec_header_hsts_maxage'] ?? 31536000 );
			$value   = 'max-age=' . $max_age;
			if ( ! empty( $s['sec_header_hsts_subdomains'] ) ) { $value .= '; includeSubDomains'; }
			if ( ! empty( $s['sec_header_hsts_preload'] ) )    { $value .= '; preload'; }
			$headers['Strict-Transport-Security'] = $value;
		}
		if ( ! empty( $s['sec_header_nosniff'] ) ) {
			$headers['X-Content-Type-Options'] = 'nosniff';
		}
		if ( ! empty( $s['sec_header_referrer'] ) ) {
			$headers['Referrer-Policy'] = $s['sec_header_referrer_value'] ?? 'strict-origin-when-cross-origin';
		}
		if ( ! empty( $s['sec_header_permissions'] ) ) {
			$headers['Permissions-Policy'] = $s['sec_header_permissions_value'] ?? 'geolocation=(), microphone=(), camera=()';
		}
		if ( ! empty( $s['sec_header_frame'] ) ) {
			$headers['X-Frame-Options'] = $s['sec_header_frame_value'] ?? 'SAMEORIGIN';
		}

		return $headers;
	}
}
